<?php
// $Id$

function node_resource_autoload_info() {
  return array(
    'NodeResourceFeedModel' => array(
      'file' => 'node_resource.models.inc',
    ),
    'NodeResourceViewFeedModel' => array(
      'file' => 'node_resource.models.inc',
    ),
  );
}

function node_resource_service_resource() {
  return array(
    'node' => array(
      '#file' => array('file' => 'inc', 'module' => 'node_resource'),
      '#retrieve' => array(
        'callback' => '_node_resource_retrieve',
        'callback arguments' => array(
          'nid' => array(
            'optional' => FALSE,
            'source' => array('path'=>0),
          ),
        ),
        'models' => array(
          'ResourceFeedModel' => array(
            'class' => 'NodeResourceFeedModel',
            'arguments' => array('source'=>'single'),
          ),
        ),
        'access callback' => '_node_resource_access',
        'access arguments' => array('retrieve'),
        'delegate access callback' => '_node_resource_access',
        'delegate access arguments' => array('retrieve', TRUE),
      ),
      '#create' => array(
        'callback' => '_node_resource_create',
        'callback arguments' => array(
          'node' => array(
            'optional' => FALSE,
            'source' => 'data',
          ),
        ),
        'models' => array(
          'ResourceFeedModel' => array(
            'class' => 'NodeResourceFeedModel',
            'arguments' => array('source'=>'single'),
          ),
        ),
        'access callback' => '_node_resource_access',
        'access arguments' => array('create'),
        'delegate access callback' => '_node_resource_access',
        'delegate access arguments' => array('create', TRUE),
      ),
      '#delete' => array(
        'callback' => '_node_resource_delete',
        'callback arguments' => array(
          'nid' => array(
            'optional' => FALSE,
            'source' => array('path'=>0),
          ),
        ),
        'access callback' => '_node_resource_access',
        'access arguments' => array('delete'),
        'delegate access callback' => '_node_resource_access',
        'delegate access arguments' => array('delete', TRUE),
      ),
      '#index' => array(
        '#retrieve' => array(
          'callback' => '_node_resource_recent',
          'callback arguments' => array(
            'page' => array(
              'optional' => TRUE,
              'default value' => 0,
              'source' => array('param'=>'page'),
            ),
          ),
          'models' => array(
            'ResourceFeedModel' => array(
              'class' => 'NodeResourceFeedModel',
            ),
            'ResourceTimeFeedModel' => array(
              'class' => 'NodeResourceFeedModel',
            ),
          ),
          'access callback' => '_node_resource_access',
          'access arguments' => array('retrieve'),
          'delegate access callback' => '_node_resource_access',
          'delegate access arguments' => array('retrieve', TRUE),
        ),
      ),
      'view' => array(
        '#retrieve' => array(
          'callback' => '_node_resource_view',
          'models' => array(
            'ResourceFeedModel' => array(
              'class' => 'NodeResourceViewFeedModel',
            ),
          ),
          'access callback' => '_node_resource_access',
          'access arguments' => array('retrieve'),
          'delegate access callback' => '_node_resource_access',
          'delegate access arguments' => array('retrieve', TRUE),
        ),
      ),
    ),
  );
}

