<?php
// $Id$

function xcal_format_rest_server_response_formatters_alter(&$formatters) {
  $formatters['xcal'] = array(
    'model' => 'ResourceTimeFeedModel',
    'mime types' => array('application/xcal+xml'),
    'view' => 'XCalFormatView',
  );
  $formatters['ical'] = array(
    'model' => 'ResourceTimeFeedModel',
    'mime types' => array('text/calendar'),
    'view' => 'XCalFormatView',
    'view arguments' => array('transform'=>'ical'),
  );
}

function _xcal_format_xcal($data) {

}

function _xcal_format_ical($data) {

}